import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { getClientIp } from "@/lib/request-ip";
import { getCurrentPlanTier } from "@/lib/plan";
import { classifyMimeType, MAX_SUMMARY_FILE_BYTES, generateFileSummary } from "@/lib/ai-summary";
import { dailySummaryLimitFor } from "@/lib/limits";
import { checkSummaryQuota, consumeSummaryQuota } from "@/lib/summary-quota";

export const maxDuration = 30;

export async function POST(req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const link = await prisma.shareLink.findUnique({ where: { slug }, include: { file: true } });
  if (!link || link.file.status !== "ACTIVE") {
    return NextResponse.json({ error: "File not found" }, { status: 404 });
  }

  const kind = classifyMimeType(link.file.mimeType);
  if (!kind || link.file.sizeBytes > BigInt(MAX_SUMMARY_FILE_BYTES)) {
    return NextResponse.json({ error: "This file type isn't eligible for AI summaries" }, { status: 400 });
  }

  // Quota is checked+consumed for THIS viewer's click unconditionally, before
  // knowing whether it'll be a fresh generation or a cache hit - clicking always
  // costs the clicking viewer, whether or not Bluto Box ends up calling DeepSeek.
  const session = await auth();
  const planTier = await getCurrentPlanTier(session?.user?.id);
  const identifier = session?.user?.id ?? `ip:${getClientIp(req)}`;
  const limit = dailySummaryLimitFor(planTier);
  const { allowed } = await checkSummaryQuota(identifier, limit);
  if (!allowed) {
    return NextResponse.json({ error: "Daily AI summary limit reached. Try again tomorrow." }, { status: 429 });
  }
  await consumeSummaryQuota(identifier);

  if (link.file.aiSummary) {
    // Already generated by an earlier viewer - serve the cached text, no new
    // DeepSeek call, but this viewer's quota above was still spent.
    return NextResponse.json({ summary: link.file.aiSummary });
  }

  const result = await generateFileSummary(link.file.id);
  if (!result.ok) {
    return NextResponse.json({ error: result.reason }, { status: 502 });
  }
  return NextResponse.json({ summary: result.summary });
}
